const data = {
  products: [
    {
      _id: "1",
      name: "Iphone 12 Pro max",
      category: "phone",
      image: "/images/product1.jpg",
      price: 300,
      brand: "Apple",
      rating: 5,
      numReview: 10,
      countInStock: 50,
      description: "sản phẩm từ apple luôn là đỉnh kout",
    },
    {
      _id: "2",
      name: "Iphone 12 Pro ",
      category: "phone",
      image: "/images/product2.jpg",
      price: 250,
      brand: "Apple",
      rating: 5,
      numReview: 10,
      countInStock: 10,
      description: "sản phẩm từ apple luôn là đỉnh kout",
    },
    {
      _id: "3",
      name: "Iphone 12 mini",
      category: "phone",
      image: "/images/product3.jpg",
      price: 220,
      brand: "Apple",
      rating: 5,
      numReview: 10,
      description: "sản phẩm từ apple luôn là đỉnh kout",
    },
    {
      _id: "4",
      name: "Iphone 12",
      category: "phone",
      image: "/images/product4.jpg",
      price: 200,
      brand: "Apple",
      rating: 4.5,
      numReview: 10,
      countInStock: 10,
      description: "sản phẩm từ apple luôn là đỉnh kout",
    },
    {
      _id: "5",
      name: "Iphone 11 Pro max",
      category: "phone",
      image: "/images/product5.jpg",
      price: 220,
      brand: "Apple",
      rating: 5,
      numReview: 10,
      countInStock: 10,
      description: "sản phẩm từ apple luôn là đỉnh kout",
    },

    {
      _id: "6",
      name: "Iphone 11 Pro ",
      category: "phone",
      image: "/images/product6.jpg",
      price: 180,
      brand: "Apple",
      rating: 4.5,
      numReview: 10,
      countInStock: 0,
      description: "sản phẩm từ apple luôn là đỉnh kout",
    },
    {
      _id: "7",
      name: "Iphone 11 ",
      category: "phone",
      image: "/images/product7.jpg",
      price: 140,
      brand: "Apple",
      rating: 3.5,
      numReview: 10,
      countInStock: 10,
      description: "sản phẩm từ apple luôn là đỉnh kout",
    },
  ],
};
export default data;
